const quizData = {
  novice: [
    // History
    {
      id: 1,
      topic: "History",
      question: "Who was the first President of the United States?",
      options: [
        "George Washington",
        "Abraham Lincoln",
        "Thomas Jefferson",
        "John Adams",
      ],
      answer: "George Washington",
    },
    {
      id: 2,
      topic: "History",
      question: "In which year did World War II end?",
      options: ["1943", "1944", "1945", "1946"],
      answer: "1945",
    },
    {
      id: 3,
      topic: "History",
      question: "Which ancient wonder was located in Alexandria, Egypt?",
      options: [
        "The Colossus of Rhodes",
        "The Lighthouse of Alexandria",
        "The Hanging Gardens",
        "The Temple of Artemis",
      ],
      answer: "The Lighthouse of Alexandria",
    },
    {
      id: 4,
      topic: "History",
      question: "Who invented the telephone?",
      options: [
        "Thomas Edison",
        "Nikola Tesla",
        "Alexander Graham Bell",
        "Guglielmo Marconi",
      ],
      answer: "Alexander Graham Bell",
    },
    {
      id: 5,
      topic: "History",
      question: "The Berlin Wall fell in which year?",
      options: ["1987", "1988", "1989", "1990"],
      answer: "1989",
    },
    {
      id: 6,
      topic: "History",
      question: "Which empire was ruled by Julius Caesar?",
      options: [
        "Greek Empire",
        "Roman Empire",
        "Ottoman Empire",
        "Byzantine Empire",
      ],
      answer: "Roman Empire",
    },
    {
      id: 7,
      topic: "History",
      question: "Who wrote the Declaration of Independence?",
      options: [
        "Benjamin Franklin",
        "George Washington",
        "Thomas Jefferson",
        "John Adams",
      ],
      answer: "Thomas Jefferson",
    },
    {
      id: 8,
      topic: "History",
      question: "In which country did the Industrial Revolution begin?",
      options: ["France", "Germany", "United States", "United Kingdom"],
      answer: "United Kingdom",
    },
    {
      id: 9,
      topic: "History",
      question: "The Titanic sank in which year?",
      options: ["1910", "1912", "1914", "1916"],
      answer: "1912",
    },
    {
      id: 10,
      topic: "History",
      question: "Who was the first man to walk on the moon?",
      options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"],
      answer: "Neil Armstrong",
    },

    // Animals
    {
      id: 11,
      topic: "Animals",
      question: "What is the largest land animal on Earth?",
      options: [
        "Hippopotamus",
        "White Rhinoceros",
        "African Elephant",
        "Giraffe",
      ],
      answer: "African Elephant",
    },
    {
      id: 12,
      topic: "Animals",
      question: "How many legs does a spider have?",
      options: ["6", "8", "10", "12"],
      answer: "8",
    },
    {
      id: 13,
      topic: "Animals",
      question: "What do you call a group of lions?",
      options: ["Pack", "Herd", "Pride", "Colony"],
      answer: "Pride",
    },
    {
      id: 14,
      topic: "Animals",
      question: "Which bird is known for its inability to fly?",
      options: ["Ostrich", "Eagle", "Sparrow", "Flamingo"],
      answer: "Ostrich",
    },
    {
      id: 15,
      topic: "Animals",
      question: "What is the fastest land animal?",
      options: ["Lion", "Horse", "Cheetah", "Greyhound"],
      answer: "Cheetah",
    },
    {
      id: 16,
      topic: "Animals",
      question: "Which animal is known as man's best friend?",
      options: ["Cat", "Horse", "Dog", "Rabbit"],
      answer: "Dog",
    },
    {
      id: 17,
      topic: "Animals",
      question: "What is the largest ocean animal?",
      options: ["Great White Shark", "Orca", "Blue Whale", "Giant Squid"],
      answer: "Blue Whale",
    },
    {
      id: 18,
      topic: "Animals",
      question: "How many hearts does an octopus have?",
      options: ["1", "2", "3", "4"],
      answer: "3",
    },
    {
      id: 19,
      topic: "Animals",
      question: "What is a baby kangaroo called?",
      options: ["Cub", "Joey", "Foal", "Kit"],
      answer: "Joey",
    },
    {
      id: 20,
      topic: "Animals",
      question: "Which animal sleeps the most hours per day?",
      options: ["Koala", "Sloth", "Cat", "Brown Bat"],
      answer: "Brown Bat",
    },

    // Geopolitics
    {
      id: 21,
      topic: "Geopolitics",
      question: "What is the capital of France?",
      options: ["Lyon", "Marseille", "Paris", "Nice"],
      answer: "Paris",
    },
    {
      id: 22,
      topic: "Geopolitics",
      question: "Which is the largest country by area?",
      options: ["Canada", "United States", "China", "Russia"],
      answer: "Russia",
    },
    {
      id: 23,
      topic: "Geopolitics",
      question: "How many countries are in the United Nations?",
      options: ["173", "193", "213", "233"],
      answer: "193",
    },
    {
      id: 24,
      topic: "Geopolitics",
      question: "What is the capital of Japan?",
      options: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"],
      answer: "Tokyo",
    },
    {
      id: 25,
      topic: "Geopolitics",
      question: "Which continent has the most countries?",
      options: ["Asia", "Europe", "South America", "Africa"],
      answer: "Africa",
    },
    {
      id: 26,
      topic: "Geopolitics",
      question: "What is the smallest country in the world?",
      options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"],
      answer: "Vatican City",
    },
    {
      id: 27,
      topic: "Geopolitics",
      question: "Which country has the longest coastline?",
      options: ["Russia", "Australia", "Norway", "Canada"],
      answer: "Canada",
    },
    {
      id: 28,
      topic: "Geopolitics",
      question: "What is the capital of Australia?",
      options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
      answer: "Canberra",
    },
    {
      id: 29,
      topic: "Geopolitics",
      question: "Which river is the longest in the world?",
      options: ["Amazon", "Mississippi", "Nile", "Yangtze"],
      answer: "Nile",
    },
    {
      id: 30,
      topic: "Geopolitics",
      question: "What is the currency of Japan?",
      options: ["Won", "Yuan", "Yen", "Baht"],
      answer: "Yen",
    },

    // Math
    {
      id: 31,
      topic: "Math",
      question: "What is 12 × 12?",
      options: ["132", "144", "156", "124"],
      answer: "144",
    },
    {
      id: 32,
      topic: "Math",
      question: "What is the square root of 64?",
      options: ["6", "7", "8", "9"],
      answer: "8",
    },
    {
      id: 33,
      topic: "Math",
      question: "How many sides does a hexagon have?",
      options: ["5", "6", "7", "8"],
      answer: "6",
    },
    {
      id: 34,
      topic: "Math",
      question: "What is 25% of 200?",
      options: ["40", "50", "60", "25"],
      answer: "50",
    },
    {
      id: 35,
      topic: "Math",
      question: "What is the value of π (pi) to two decimal places?",
      options: ["3.12", "3.14", "3.16", "3.18"],
      answer: "3.14",
    },
    {
      id: 36,
      topic: "Math",
      question: "What is 2 to the power of 10?",
      options: ["512", "1024", "2048", "256"],
      answer: "1024",
    },
    {
      id: 37,
      topic: "Math",
      question: "What is the perimeter of a square with side length 5?",
      options: ["20", "25", "10", "15"],
      answer: "20",
    },
    {
      id: 38,
      topic: "Math",
      question: "How many degrees are in a right angle?",
      options: ["45°", "90°", "180°", "360°"],
      answer: "90°",
    },
    {
      id: 39,
      topic: "Math",
      question: "What is 100 ÷ 4?",
      options: ["20", "25", "30", "40"],
      answer: "25",
    },
    {
      id: 40,
      topic: "Math",
      question: "Which of these is a prime number?",
      options: ["9", "15", "17", "21"],
      answer: "17",
    },

    // Coding
    {
      id: 41,
      topic: "Coding",
      question: "What does HTML stand for?",
      options: [
        "Hyper Text Markup Language",
        "High Tech Machine Language",
        "Home Tool Markup Language",
        "Hyperlink Text Mode Language",
      ],
      answer: "Hyper Text Markup Language",
    },
    {
      id: 42,
      topic: "Coding",
      question: "Which symbol is used for comments in Python?",
      options: ["//", "/*", "#", "--"],
      answer: "#",
    },
    {
      id: 43,
      topic: "Coding",
      question: "What does CSS stand for?",
      options: [
        "Computer Style Sheets",
        "Cascading Style Sheets",
        "Creative Style Syntax",
        "Colorful Style Sheets",
      ],
      answer: "Cascading Style Sheets",
    },
    {
      id: 44,
      topic: "Coding",
      question: "Which of the following is a programming language?",
      options: ["HTML", "CSS", "Python", "JSON"],
      answer: "Python",
    },
    {
      id: 45,
      topic: "Coding",
      question: "What is the output of print(2 + 3) in Python?",
      options: ["23", "5", "2+3", "Error"],
      answer: "5",
    },
    {
      id: 46,
      topic: "Coding",
      question: "In programming, what does a loop do?",
      options: [
        "Stops the program",
        "Repeats a block of code",
        "Deletes variables",
        "Connects to internet",
      ],
      answer: "Repeats a block of code",
    },
    {
      id: 47,
      topic: "Coding",
      question: "What does URL stand for?",
      options: [
        "Universal Resource Link",
        "Uniform Resource Locator",
        "Unified Record Loader",
        "User Reference Language",
      ],
      answer: "Uniform Resource Locator",
    },
    {
      id: 48,
      topic: "Coding",
      question: "Which data type stores True or False?",
      options: ["Integer", "String", "Boolean", "Float"],
      answer: "Boolean",
    },
    {
      id: 49,
      topic: "Coding",
      question: "What is the first index in most programming language arrays?",
      options: ["0", "1", "-1", "10"],
      answer: "0",
    },
    {
      id: 50,
      topic: "Coding",
      question: "What does the Internet use to identify devices?",
      options: ["MAC Address", "IP Address", "URL", "DNS"],
      answer: "IP Address",
    },

    // Science
    {
      id: 51,
      topic: "Science",
      question: "What is the chemical symbol for water?",
      options: ["WA", "H2O", "HO2", "W2O"],
      answer: "H2O",
    },
    {
      id: 52,
      topic: "Science",
      question: "How many planets are in our solar system?",
      options: ["7", "8", "9", "10"],
      answer: "8",
    },
    {
      id: 53,
      topic: "Science",
      question: "What gas do plants absorb from the atmosphere?",
      options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
      answer: "Carbon Dioxide",
    },
    {
      id: 54,
      topic: "Science",
      question: "What is the center of an atom called?",
      options: ["Electron", "Proton", "Nucleus", "Neutron"],
      answer: "Nucleus",
    },
    {
      id: 55,
      topic: "Science",
      question: "Which planet is closest to the Sun?",
      options: ["Venus", "Earth", "Mars", "Mercury"],
      answer: "Mercury",
    },
    {
      id: 56,
      topic: "Science",
      question: "What is the speed of light approximately?",
      options: ["300,000 km/s", "30,000 km/s", "3,000 km/s", "3,000,000 km/s"],
      answer: "300,000 km/s",
    },
    {
      id: 57,
      topic: "Science",
      question: "Which organ pumps blood throughout the human body?",
      options: ["Lungs", "Brain", "Liver", "Heart"],
      answer: "Heart",
    },
    {
      id: 58,
      topic: "Science",
      question: "What force keeps us on the ground?",
      options: ["Magnetism", "Friction", "Gravity", "Pressure"],
      answer: "Gravity",
    },
    {
      id: 59,
      topic: "Science",
      question: "What is the boiling point of water in Celsius?",
      options: ["90°C", "95°C", "100°C", "110°C"],
      answer: "100°C",
    },
    {
      id: 60,
      topic: "Science",
      question: "How many bones are in the adult human body?",
      options: ["186", "206", "226", "246"],
      answer: "206",
    },

    // General Knowledge
    {
      id: 61,
      topic: "General",
      question: "What is the color of the sky on a clear day?",
      options: ["Green", "Blue", "Gray", "White"],
      answer: "Blue",
    },
    {
      id: 62,
      topic: "General",
      question: "How many colors are in a rainbow?",
      options: ["5", "6", "7", "8"],
      answer: "7",
    },
    {
      id: 63,
      topic: "General",
      question: "Which is the tallest mountain in the world?",
      options: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"],
      answer: "Mount Everest",
    },
    {
      id: 64,
      topic: "General",
      question: "What is the most widely spoken language in the world?",
      options: ["English", "Spanish", "Mandarin Chinese", "Hindi"],
      answer: "Mandarin Chinese",
    },
    {
      id: 65,
      topic: "General",
      question: "How many days are in a leap year?",
      options: ["364", "365", "366", "367"],
      answer: "366",
    },
    {
      id: 66,
      topic: "General",
      question: "Which is the largest ocean on Earth?",
      options: ["Atlantic", "Indian", "Arctic", "Pacific"],
      answer: "Pacific",
    },
    {
      id: 67,
      topic: "General",
      question: "How many hours are in a day?",
      options: ["12", "24", "36", "48"],
      answer: "24",
    },
    {
      id: 68,
      topic: "General",
      question: "Which planet is known as the Red Planet?",
      options: ["Venus", "Jupiter", "Mars", "Saturn"],
      answer: "Mars",
    },
    {
      id: 69,
      topic: "General",
      question: "What is the capital of the United States?",
      options: ["New York", "Los Angeles", "Chicago", "Washington D.C."],
      answer: "Washington D.C.",
    },
    {
      id: 70,
      topic: "General",
      question: "Which gas do humans breathe in to survive?",
      options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
      answer: "Oxygen",
    },
    {
      id: 71,
      topic: "History",
      question:
        "Who was the Egyptian queen famous for her relationships with Julius Caesar and Mark Antony?",
      options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"],
      answer: "Cleopatra",
    },
    {
      id: 72,
      topic: "Animals",
      question: "What is the tallest animal in the world?",
      options: ["Elephant", "Giraffe", "Horse", "Camel"],
      answer: "Giraffe",
    },
    {
      id: 73,
      topic: "Geopolitics",
      question: "What is the capital of Brazil?",
      options: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
      answer: "Brasília",
    },
    {
      id: 74,
      topic: "Math",
      question: "What is 15 + 27?",
      options: ["40", "42", "44", "46"],
      answer: "42",
    },
    {
      id: 75,
      topic: "Science",
      question: "What is the largest planet in our solar system?",
      options: ["Saturn", "Uranus", "Jupiter", "Neptune"],
      answer: "Jupiter",
    },
    {
      id: 76,
      topic: "Coding",
      question: "What tag is used to create a hyperlink in HTML?",
      options: ["<link>", "<href>", "<a>", "<url>"],
      answer: "<a>",
    },
    {
      id: 77,
      topic: "General",
      question: "Who painted the Mona Lisa?",
      options: ["Michelangelo", "Rafael", "Leonardo da Vinci", "Donatello"],
      answer: "Leonardo da Vinci",
    },
    {
      id: 78,
      topic: "Science",
      question: "What is the chemical symbol for gold?",
      options: ["Gd", "Go", "Au", "Ag"],
      answer: "Au",
    },
    {
      id: 79,
      topic: "History",
      question:
        "Which country gifted the Statue of Liberty to the United States?",
      options: ["Britain", "Germany", "France", "Italy"],
      answer: "France",
    },
    {
      id: 80,
      topic: "Animals",
      question: "What do butterflies taste with?",
      options: ["Tongue", "Antennae", "Feet", "Eyes"],
      answer: "Feet",
    },
    {
      id: 81,
      topic: "Geopolitics",
      question: "What is the most populated country in the world?",
      options: ["United States", "India", "China", "Indonesia"],
      answer: "India",
    },
    {
      id: 82,
      topic: "Math",
      question:
        "If a triangle has angles of 60° and 80°, what is the third angle?",
      options: ["30°", "40°", "50°", "60°"],
      answer: "40°",
    },
    {
      id: 83,
      topic: "Coding",
      question: "What does RAM stand for?",
      options: [
        "Random Access Memory",
        "Read And Memorize",
        "Rapid Application Module",
        "Remote Access Memory",
      ],
      answer: "Random Access Memory",
    },
    {
      id: 84,
      topic: "Science",
      question: "What is the hardest natural substance on Earth?",
      options: ["Gold", "Iron", "Diamond", "Quartz"],
      answer: "Diamond",
    },
    {
      id: 85,
      topic: "General",
      question: "How many strings does a standard guitar have?",
      options: ["4", "5", "6", "8"],
      answer: "6",
    },
    {
      id: 86,
      topic: "History",
      question: "Who was the first woman to win a Nobel Prize?",
      options: [
        "Rosalind Franklin",
        "Marie Curie",
        "Ada Lovelace",
        "Florence Nightingale",
      ],
      answer: "Marie Curie",
    },
    {
      id: 87,
      topic: "Animals",
      question: "How long is an elephant's pregnancy (gestation)?",
      options: ["6 months", "12 months", "18 months", "22 months"],
      answer: "22 months",
    },
    {
      id: 88,
      topic: "Geopolitics",
      question: "What is the official language of Brazil?",
      options: ["Spanish", "Portuguese", "French", "English"],
      answer: "Portuguese",
    },
    {
      id: 89,
      topic: "Math",
      question: "What is the result of 9² - 4²?",
      options: ["65", "77", "81", "65"],
      answer: "65",
    },
    {
      id: 90,
      topic: "Science",
      question: "What does DNA stand for?",
      options: [
        "Deoxyribonucleic Acid",
        "Dynamic Natural Atom",
        "Dual Nucleic Array",
        "Digital Nucleotide Agent",
      ],
      answer: "Deoxyribonucleic Acid",
    },
    {
      id: 91,
      topic: "Coding",
      question: "Which of these is NOT a web browser?",
      options: ["Firefox", "Chrome", "Linux", "Safari"],
      answer: "Linux",
    },
    {
      id: 92,
      topic: "General",
      question: "What sport is played at Wimbledon?",
      options: ["Cricket", "Tennis", "Golf", "Badminton"],
      answer: "Tennis",
    },
    {
      id: 93,
      topic: "History",
      question:
        "The Great Wall of China was primarily built to protect against whom?",
      options: ["Romans", "Japanese", "Northern nomadic tribes", "Persians"],
      answer: "Northern nomadic tribes",
    },
    {
      id: 94,
      topic: "Animals",
      question: "What is the only mammal capable of true flight?",
      options: ["Flying squirrel", "Flying fish", "Bat", "Sugar glider"],
      answer: "Bat",
    },
    {
      id: 95,
      topic: "Math",
      question: "What is the next number in the sequence: 2, 4, 8, 16, ___?",
      options: ["20", "24", "32", "64"],
      answer: "32",
    },
    {
      id: 96,
      topic: "Science",
      question: "Which layer of Earth is liquid?",
      options: ["Crust", "Mantle", "Outer Core", "Inner Core"],
      answer: "Outer Core",
    },
    {
      id: 97,
      topic: "Geopolitics",
      question: "Which city is known as 'The Big Apple'?",
      options: ["Chicago", "Los Angeles", "New York City", "Miami"],
      answer: "New York City",
    },
    {
      id: 98,
      topic: "General",
      question: "In which continent is Egypt located?",
      options: ["Asia", "Europe", "Africa", "Middle East"],
      answer: "Africa",
    },
    {
      id: 99,
      topic: "Coding",
      question: "What does 'www' stand for in a web address?",
      options: [
        "World Wide Web",
        "World Web Works",
        "Wide World Web",
        "Web World Works",
      ],
      answer: "World Wide Web",
    },
    {
      id: 100,
      topic: "General",
      question: "What is the national sport of Canada?",
      options: ["Basketball", "Ice Hockey", "Baseball", "Lacrosse"],
      answer: "Lacrosse",
    },
  ],

  expert: [
    // History
    {
      id: 101,
      topic: "History",
      question: "The Treaty of Westphalia (1648) ended which wars?",
      options: [
        "The Napoleonic Wars",
        "The Thirty Years' War and the Eighty Years' War",
        "The Crusades",
        "The Hundred Years' War",
      ],
      answer: "The Thirty Years' War and the Eighty Years' War",
    },
    {
      id: 102,
      topic: "History",
      question:
        "Which empire was known as the 'Sick Man of Europe' in the 19th century?",
      options: [
        "Austro-Hungarian Empire",
        "Russian Empire",
        "Ottoman Empire",
        "Byzantine Empire",
      ],
      answer: "Ottoman Empire",
    },
    {
      id: 103,
      topic: "History",
      question: "Who was the last Tsar of Russia?",
      options: ["Alexander III", "Nicholas II", "Peter the Great", "Paul I"],
      answer: "Nicholas II",
    },
    {
      id: 104,
      topic: "History",
      question:
        "The Battle of Hastings in 1066 resulted in which country's conquest?",
      options: ["France", "Germany", "England", "Scotland"],
      answer: "England",
    },
    {
      id: 105,
      topic: "History",
      question: "What was the name of Napoleon's final defeat?",
      options: [
        "Battle of Trafalgar",
        "Battle of Leipzig",
        "Battle of Waterloo",
        "Battle of Austerlitz",
      ],
      answer: "Battle of Waterloo",
    },
    {
      id: 106,
      topic: "History",
      question: "Which ancient civilization built the city of Machu Picchu?",
      options: ["Maya", "Aztec", "Inca", "Olmec"],
      answer: "Inca",
    },
    {
      id: 107,
      topic: "History",
      question: "Who was the founder of the Mongol Empire?",
      options: ["Kublai Khan", "Tamerlane", "Genghis Khan", "Ögedei Khan"],
      answer: "Genghis Khan",
    },
    {
      id: 108,
      topic: "History",
      question: "In what year did the French Revolution begin?",
      options: ["1776", "1789", "1799", "1804"],
      answer: "1789",
    },
    {
      id: 109,
      topic: "History",
      question:
        "Which country was NOT part of the Allied Powers in World War I?",
      options: ["France", "Russia", "Ottoman Empire", "United Kingdom"],
      answer: "Ottoman Empire",
    },
    {
      id: 110,
      topic: "History",
      question:
        "The Meiji Restoration transformed which country into a modern industrial state?",
      options: ["China", "Korea", "Japan", "Vietnam"],
      answer: "Japan",
    },

    // Animals
    {
      id: 111,
      topic: "Animals",
      question: "What is the gestation period of a blue whale?",
      options: ["6 months", "8 months", "10-12 months", "14 months"],
      answer: "10-12 months",
    },
    {
      id: 112,
      topic: "Animals",
      question: "Which bird has the largest wingspan?",
      options: ["Bald Eagle", "Albatross", "Condor", "Pelican"],
      answer: "Albatross",
    },
    {
      id: 113,
      topic: "Animals",
      question: "What type of animal is a Komodo dragon?",
      options: ["Salamander", "Crocodilian", "Monitor lizard", "Giant gecko"],
      answer: "Monitor lizard",
    },
    {
      id: 114,
      topic: "Animals",
      question:
        "Which fish can generate electric fields to navigate and communicate?",
      options: ["Electric ray", "Electric eel", "Shark", "All of the above"],
      answer: "All of the above",
    },
    {
      id: 115,
      topic: "Animals",
      question: "How many species of big cats are recognized by scientists?",
      options: ["4", "5", "7", "9"],
      answer: "7",
    },
    {
      id: 116,
      topic: "Animals",
      question:
        "What is the term for an animal that eats both plants and meat?",
      options: ["Herbivore", "Carnivore", "Omnivore", "Insectivore"],
      answer: "Omnivore",
    },
    {
      id: 117,
      topic: "Animals",
      question: "Which animal has the most teeth?",
      options: ["Great White Shark", "Snail", "Crocodile", "Hippopotamus"],
      answer: "Snail",
    },
    {
      id: 118,
      topic: "Animals",
      question: "What is the primary diet of a giant panda?",
      options: ["Fish", "Bamboo", "Insects", "Fruit"],
      answer: "Bamboo",
    },
    {
      id: 119,
      topic: "Animals",
      question:
        "Which animal has been on Earth the longest without significant evolutionary change?",
      options: ["Crocodile", "Horseshoe Crab", "Coelacanth", "Nautilus"],
      answer: "Horseshoe Crab",
    },
    {
      id: 120,
      topic: "Animals",
      question: "What is the name for a group of crows?",
      options: ["Flock", "Pack", "Murder", "Colony"],
      answer: "Murder",
    },

    // Geopolitics
    {
      id: 121,
      topic: "Geopolitics",
      question: "The Strait of Hormuz separates which two bodies of water?",
      options: [
        "Mediterranean and Red Sea",
        "Persian Gulf and Gulf of Oman",
        "Black Sea and Caspian Sea",
        "Red Sea and Indian Ocean",
      ],
      answer: "Persian Gulf and Gulf of Oman",
    },
    {
      id: 122,
      topic: "Geopolitics",
      question: "Which island is disputed between China and Taiwan?",
      options: ["Hainan", "Kinmen", "Matsu", "All of the above"],
      answer: "All of the above",
    },
    {
      id: 123,
      topic: "Geopolitics",
      question: "ASEAN was founded in which year?",
      options: ["1957", "1963", "1967", "1971"],
      answer: "1967",
    },
    {
      id: 124,
      topic: "Geopolitics",
      question: "Which country has the most official languages?",
      options: ["Switzerland", "South Africa", "India", "Papua New Guinea"],
      answer: "South Africa",
    },
    {
      id: 125,
      topic: "Geopolitics",
      question:
        "The 'Five Eyes' intelligence alliance consists of which countries?",
      options: [
        "US, UK, France, Canada, Australia",
        "US, UK, Canada, Australia, New Zealand",
        "US, UK, Germany, France, Italy",
        "US, UK, Israel, Canada, Japan",
      ],
      answer: "US, UK, Canada, Australia, New Zealand",
    },
    {
      id: 126,
      topic: "Geopolitics",
      question: "What is the largest landlocked country in the world?",
      options: ["Mongolia", "Kazakhstan", "Chad", "Bolivia"],
      answer: "Kazakhstan",
    },
    {
      id: 127,
      topic: "Geopolitics",
      question: "Which mountain range separates Europe and Asia?",
      options: ["Alps", "Carpathians", "Ural Mountains", "Caucasus"],
      answer: "Ural Mountains",
    },
    {
      id: 128,
      topic: "Geopolitics",
      question: "In which city is the International Court of Justice located?",
      options: ["Brussels", "Geneva", "The Hague", "Vienna"],
      answer: "The Hague",
    },
    {
      id: 129,
      topic: "Geopolitics",
      question: "Which country holds the most nuclear warheads?",
      options: ["United States", "China", "Russia", "France"],
      answer: "Russia",
    },
    {
      id: 130,
      topic: "Geopolitics",
      question: "What does NATO stand for?",
      options: [
        "North Atlantic Treaty Organization",
        "National Alliance Treaty of Operations",
        "Northern Army Treaty Organization",
        "North American Treaty Organization",
      ],
      answer: "North Atlantic Treaty Organization",
    },

    // Math
    {
      id: 131,
      topic: "Math",
      question: "What is the derivative of sin(x)?",
      options: ["-sin(x)", "cos(x)", "-cos(x)", "tan(x)"],
      answer: "cos(x)",
    },
    {
      id: 132,
      topic: "Math",
      question: "What is the sum of interior angles of a pentagon?",
      options: ["360°", "450°", "540°", "720°"],
      answer: "540°",
    },
    {
      id: 133,
      topic: "Math",
      question: "What is the 10th Fibonacci number?",
      options: ["34", "44", "55", "65"],
      answer: "55",
    },
    {
      id: 134,
      topic: "Math",
      question: "If log₂(x) = 5, what is x?",
      options: ["10", "16", "25", "32"],
      answer: "32",
    },
    {
      id: 135,
      topic: "Math",
      question: "What is the formula for the area of a circle?",
      options: ["2πr", "πr²", "πd", "2πd"],
      answer: "πr²",
    },
    {
      id: 136,
      topic: "Math",
      question: "How many prime numbers are less than 50?",
      options: ["13", "15", "17", "19"],
      answer: "15",
    },
    {
      id: 137,
      topic: "Math",
      question: "What is the result of i² in complex numbers?",
      options: ["1", "-1", "i", "-i"],
      answer: "-1",
    },
    {
      id: 138,
      topic: "Math",
      question: "What is the Greatest Common Divisor (GCD) of 48 and 36?",
      options: ["6", "8", "10", "12"],
      answer: "12",
    },
    {
      id: 139,
      topic: "Math",
      question: "A set has 4 elements. How many subsets does it have?",
      options: ["8", "12", "16", "24"],
      answer: "16",
    },
    {
      id: 140,
      topic: "Math",
      question:
        "What is the standard deviation of the data set {2, 4, 4, 4, 5, 5, 7, 9}?",
      options: ["1", "2", "3", "4"],
      answer: "2",
    },

    // Coding
    {
      id: 141,
      topic: "Coding",
      question: "What is the time complexity of binary search?",
      options: ["O(n)", "O(n log n)", "O(log n)", "O(1)"],
      answer: "O(log n)",
    },
    {
      id: 142,
      topic: "Coding",
      question: "In JavaScript, what does '===' (triple equals) check for?",
      options: [
        "Value equality only",
        "Type equality only",
        "Value and type equality",
        "Reference equality",
      ],
      answer: "Value and type equality",
    },
    {
      id: 143,
      topic: "Coding",
      question: "What is a RESTful API?",
      options: [
        "A database type",
        "A UI framework",
        "An architectural style for APIs using HTTP",
        "A programming language",
      ],
      answer: "An architectural style for APIs using HTTP",
    },
    {
      id: 144,
      topic: "Coding",
      question: "What does SQL stand for?",
      options: [
        "Sequential Query Language",
        "Structured Query Language",
        "System Query Logic",
        "Simple Query Language",
      ],
      answer: "Structured Query Language",
    },
    {
      id: 145,
      topic: "Coding",
      question:
        "Which sorting algorithm has the best average-case time complexity?",
      options: [
        "Bubble Sort",
        "Merge Sort",
        "Selection Sort",
        "Insertion Sort",
      ],
      answer: "Merge Sort",
    },
    {
      id: 146,
      topic: "Coding",
      question: "What is polymorphism in OOP?",
      options: [
        "A class inheriting from another",
        "An object taking many forms",
        "Hiding internal data",
        "Grouping data and methods",
      ],
      answer: "An object taking many forms",
    },
    {
      id: 147,
      topic: "Coding",
      question: "What is a 'null pointer exception'?",
      options: [
        "Accessing an out-of-bounds array",
        "Dividing by zero",
        "Dereferencing a null reference",
        "Stack overflow",
      ],
      answer: "Dereferencing a null reference",
    },
    {
      id: 148,
      topic: "Coding",
      question: "Which HTTP status code indicates 'Not Found'?",
      options: ["200", "301", "403", "404"],
      answer: "404",
    },
    {
      id: 149,
      topic: "Coding",
      question: "What is a 'stack' data structure?",
      options: [
        "First-In First-Out",
        "Last-In First-Out",
        "Random access storage",
        "Priority queue",
      ],
      answer: "Last-In First-Out",
    },
    {
      id: 150,
      topic: "Coding",
      question: "Which language is primarily used for machine learning and AI?",
      options: ["Java", "C++", "Python", "Swift"],
      answer: "Python",
    },

    // Science
    {
      id: 151,
      topic: "Science",
      question: "What is Avogadro's number?",
      options: ["6.022 × 10²²", "6.022 × 10²³", "6.022 × 10²⁴", "6.022 × 10²¹"],
      answer: "6.022 × 10²³",
    },
    {
      id: 152,
      topic: "Science",
      question: "Which quantum number describes the shape of an orbital?",
      options: ["Principal (n)", "Azimuthal (l)", "Magnetic (m)", "Spin (s)"],
      answer: "Azimuthal (l)",
    },
    {
      id: 153,
      topic: "Science",
      question: "What is the powerhouse of the cell?",
      options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
      answer: "Mitochondria",
    },
    {
      id: 154,
      topic: "Science",
      question: "What type of radiation has the longest wavelength?",
      options: ["Gamma rays", "X-rays", "Ultraviolet", "Radio waves"],
      answer: "Radio waves",
    },
    {
      id: 155,
      topic: "Science",
      question: "What is Newton's second law of motion?",
      options: ["F = ma", "E = mc²", "PV = nRT", "v = u + at"],
      answer: "F = ma",
    },
    {
      id: 156,
      topic: "Science",
      question: "The pH of pure water at 25°C is:",
      options: ["6", "7", "8", "9"],
      answer: "7",
    },
    {
      id: 157,
      topic: "Science",
      question: "Which element has the symbol 'Fe'?",
      options: ["Fluorine", "Francium", "Iron", "Fermium"],
      answer: "Iron",
    },
    {
      id: 158,
      topic: "Science",
      question: "What is the half-life concept used for?",
      options: [
        "Measuring gravity",
        "Describing radioactive decay rates",
        "Calculating wave frequency",
        "Measuring light speed",
      ],
      answer: "Describing radioactive decay rates",
    },
    {
      id: 159,
      topic: "Science",
      question: "What is the process of cell division called?",
      options: ["Meiosis", "Osmosis", "Mitosis", "Photosynthesis"],
      answer: "Mitosis",
    },
    {
      id: 160,
      topic: "Science",
      question:
        "Which law states that gas pressure and volume are inversely related at constant temperature?",
      options: [
        "Charles's Law",
        "Dalton's Law",
        "Gay-Lussac's Law",
        "Boyle's Law",
      ],
      answer: "Boyle's Law",
    },

    // General Knowledge
    {
      id: 161,
      topic: "General",
      question: "Who wrote '1984'?",
      options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"],
      answer: "George Orwell",
    },
    {
      id: 162,
      topic: "General",
      question: "Which element is the most abundant in the Earth's crust?",
      options: ["Silicon", "Iron", "Oxygen", "Aluminum"],
      answer: "Oxygen",
    },
    {
      id: 163,
      topic: "General",
      question: "Who composed the 'Moonlight Sonata'?",
      options: ["Mozart", "Bach", "Beethoven", "Chopin"],
      answer: "Beethoven",
    },
    {
      id: 164,
      topic: "General",
      question: "What is the rarest blood type?",
      options: ["A-", "B-", "AB-", "O-"],
      answer: "AB-",
    },
    {
      id: 165,
      topic: "General",
      question: "In which year was the Internet invented?",
      options: ["1969", "1975", "1983", "1991"],
      answer: "1983",
    },
    {
      id: 166,
      topic: "General",
      question: "What is the name of the deepest ocean trench?",
      options: [
        "Puerto Rico Trench",
        "Java Trench",
        "Mariana Trench",
        "Philippine Trench",
      ],
      answer: "Mariana Trench",
    },
    {
      id: 167,
      topic: "General",
      question: "Which company created the iPhone?",
      options: ["Samsung", "Google", "Apple", "Microsoft"],
      answer: "Apple",
    },
    {
      id: 168,
      topic: "General",
      question: "What is the study of earthquakes called?",
      options: ["Geology", "Volcanology", "Seismology", "Tectonics"],
      answer: "Seismology",
    },
    {
      id: 169,
      topic: "General",
      question: "In chess, which piece can only move diagonally?",
      options: ["Rook", "Knight", "Bishop", "King"],
      answer: "Bishop",
    },
    {
      id: 170,
      topic: "General",
      question: "What is the largest desert in the world?",
      options: [
        "Arabian Desert",
        "Gobi Desert",
        "Sahara Desert",
        "Antarctic Desert",
      ],
      answer: "Antarctic Desert",
    },
    {
      id: 171,
      topic: "History",
      question:
        "The Rosetta Stone was key to deciphering which ancient script?",
      options: ["Cuneiform", "Linear B", "Egyptian Hieroglyphics", "Sanskrit"],
      answer: "Egyptian Hieroglyphics",
    },
    {
      id: 172,
      topic: "Animals",
      question: "Which bird migrates the farthest annually?",
      options: [
        "Monarch Butterfly",
        "Arctic Tern",
        "Bar-tailed Godwit",
        "Humpback Whale",
      ],
      answer: "Arctic Tern",
    },
    {
      id: 173,
      topic: "Geopolitics",
      question: "Which countries share the longest international border?",
      options: [
        "USA and Mexico",
        "Russia and China",
        "USA and Canada",
        "Argentina and Chile",
      ],
      answer: "USA and Canada",
    },
    {
      id: 174,
      topic: "Math",
      question: "What is Euler's identity: e^(iπ) + ___ = 0?",
      options: ["0", "1", "i", "π"],
      answer: "1",
    },
    {
      id: 175,
      topic: "Science",
      question: "What is dark matter?",
      options: [
        "Black holes combined",
        "An invisible substance making up ~27% of the universe",
        "The space between galaxies",
        "Antimatter",
      ],
      answer: "An invisible substance making up ~27% of the universe",
    },
    {
      id: 176,
      topic: "Coding",
      question: "What does 'async/await' do in JavaScript?",
      options: [
        "Stops code execution",
        "Enables synchronous-looking asynchronous code",
        "Creates multiple threads",
        "Compiles code ahead of time",
      ],
      answer: "Enables synchronous-looking asynchronous code",
    },
    {
      id: 177,
      topic: "General",
      question: "Who developed the theory of general relativity?",
      options: ["Isaac Newton", "Max Planck", "Albert Einstein", "Niels Bohr"],
      answer: "Albert Einstein",
    },
    {
      id: 178,
      topic: "Science",
      question: "What is the difference between fission and fusion?",
      options: [
        "They are the same process",
        "Fission splits atoms; fusion joins atoms",
        "Fusion splits atoms; fission joins atoms",
        "Neither involves atoms",
      ],
      answer: "Fission splits atoms; fusion joins atoms",
    },
    {
      id: 179,
      topic: "History",
      question: "Which city was the capital of the Byzantine Empire?",
      options: ["Athens", "Alexandria", "Constantinople", "Rome"],
      answer: "Constantinople",
    },
    {
      id: 180,
      topic: "Coding",
      question:
        "What is the main purpose of a version control system like Git?",
      options: [
        "Compile code",
        "Track and manage code changes",
        "Debug programs",
        "Host websites",
      ],
      answer: "Track and manage code changes",
    },
    {
      id: 181,
      topic: "Science",
      question: "What is the second most abundant gas in Earth's atmosphere?",
      options: ["Carbon Dioxide", "Argon", "Oxygen", "Nitrogen"],
      answer: "Oxygen",
    },
    {
      id: 182,
      topic: "History",
      question: "The Magna Carta was signed in which year?",
      options: ["1015", "1115", "1215", "1315"],
      answer: "1215",
    },
    {
      id: 183,
      topic: "Coding",
      question: "What is 'Big O notation' used to describe?",
      options: [
        "Memory size",
        "Algorithm complexity",
        "Data types",
        "Network speed",
      ],
      answer: "Algorithm complexity",
    },
    {
      id: 184,
      topic: "Animals",
      question: "What is the scientific study of insects called?",
      options: ["Herpetology", "Ornithology", "Entomology", "Arachnology"],
      answer: "Entomology",
    },
    {
      id: 185,
      topic: "Geopolitics",
      question:
        "What is the principle of 'Mutually Assured Destruction' (MAD)?",
      options: [
        "Economic sanctions",
        "Nuclear deterrence doctrine",
        "Military alliance pledge",
        "Trade war strategy",
      ],
      answer: "Nuclear deterrence doctrine",
    },
    {
      id: 186,
      topic: "Math",
      question:
        "What is the name of the theorem relating sides of a right triangle?",
      options: [
        "Euclid's Theorem",
        "Fermat's Last Theorem",
        "Pythagorean Theorem",
        "Pascal's Theorem",
      ],
      answer: "Pythagorean Theorem",
    },
    {
      id: 187,
      topic: "General",
      question: "Who was the first person to orbit Earth?",
      options: ["Neil Armstrong", "Buzz Aldrin", "John Glenn", "Yuri Gagarin"],
      answer: "Yuri Gagarin",
    },
    {
      id: 188,
      topic: "Science",
      question:
        "Which scientist proposed the heliocentric model of the solar system?",
      options: ["Galileo", "Kepler", "Copernicus", "Newton"],
      answer: "Copernicus",
    },
    {
      id: 189,
      topic: "History",
      question:
        "What was the name of the economic policy of openness in the Soviet Union under Gorbachev?",
      options: ["Perestroika", "Glasnost", "Détente", "Ostpolitik"],
      answer: "Glasnost",
    },
    {
      id: 190,
      topic: "Coding",
      question: "What is 'recursion' in programming?",
      options: [
        "A type of loop",
        "A function that calls itself",
        "A form of inheritance",
        "A debugging technique",
      ],
      answer: "A function that calls itself",
    },
    {
      id: 191,
      topic: "Animals",
      question: "Which mammal lays eggs?",
      options: ["Koala", "Wombat", "Platypus", "Tasmanian Devil"],
      answer: "Platypus",
    },
    {
      id: 192,
      topic: "Geopolitics",
      question: "How many members does the G7 group have?",
      options: ["5", "6", "7", "8"],
      answer: "7",
    },
    {
      id: 193,
      topic: "Math",
      question: "What is the formula for compound interest?",
      options: [
        "A = P(1 + rt)",
        "A = P(1 + r/n)^(nt)",
        "A = P + Prt",
        "A = Pe^(rt)",
      ],
      answer: "A = P(1 + r/n)^(nt)",
    },
    {
      id: 194,
      topic: "Science",
      question: "What particle carries electromagnetic force?",
      options: ["Graviton", "Gluon", "Photon", "Neutrino"],
      answer: "Photon",
    },
    {
      id: 195,
      topic: "General",
      question: "Who wrote 'The Origin of Species'?",
      options: [
        "Gregor Mendel",
        "Louis Pasteur",
        "Charles Darwin",
        "Alfred Russel Wallace",
      ],
      answer: "Charles Darwin",
    },
    {
      id: 196,
      topic: "History",
      question: "The Silk Road primarily connected which two regions?",
      options: [
        "Europe and Africa",
        "China and Europe",
        "India and the Middle East",
        "Russia and China",
      ],
      answer: "China and Europe",
    },
    {
      id: 197,
      topic: "Coding",
      question: "What is 'encapsulation' in object-oriented programming?",
      options: [
        "Inheriting properties",
        "Bundling data and methods together",
        "Creating multiple instances",
        "Overriding parent methods",
      ],
      answer: "Bundling data and methods together",
    },
    {
      id: 198,
      topic: "Science",
      question: "What is the Doppler Effect?",
      options: [
        "Light bending around mass",
        "Change in wave frequency due to motion",
        "Sound traveling faster than light",
        "Reflection of electromagnetic waves",
      ],
      answer: "Change in wave frequency due to motion",
    },
    {
      id: 199,
      topic: "Geopolitics",
      question: "Which organization oversees global trade rules?",
      options: ["IMF", "World Bank", "WTO", "OECD"],
      answer: "WTO",
    },
    {
      id: 200,
      topic: "General",
      question: "Who discovered penicillin?",
      options: [
        "Louis Pasteur",
        "Alexander Fleming",
        "Joseph Lister",
        "Robert Koch",
      ],
      answer: "Alexander Fleming",
    },
  ],

  genius: [
    // History
    {
      id: 201,
      topic: "History",
      question:
        "The Warring States period in China ended with the unification under which dynasty?",
      options: ["Han", "Zhou", "Qin", "Tang"],
      answer: "Qin",
    },
    {
      id: 202,
      topic: "History",
      question: "Which philosopher tutored Alexander the Great?",
      options: ["Plato", "Socrates", "Aristotle", "Pythagoras"],
      answer: "Aristotle",
    },
    {
      id: 203,
      topic: "History",
      question:
        "The Defenestration of Prague in 1618 triggered which major conflict?",
      options: [
        "The Hundred Years' War",
        "The Thirty Years' War",
        "The Seven Years' War",
        "The War of Roses",
      ],
      answer: "The Thirty Years' War",
    },
    {
      id: 204,
      topic: "History",
      question:
        "What was the name of the policy that led to mass starvation in Soviet Ukraine in 1932–33?",
      options: [
        "Collectivization",
        "Kulak Liquidation",
        "Holodomor",
        "NEP Reversal",
      ],
      answer: "Holodomor",
    },
    {
      id: 205,
      topic: "History",
      question:
        "The Peloponnesian War was primarily between which two city-states?",
      options: [
        "Athens and Corinth",
        "Sparta and Thebes",
        "Athens and Sparta",
        "Corinth and Thebes",
      ],
      answer: "Athens and Sparta",
    },
    {
      id: 206,
      topic: "History",
      question: "Which Mughal emperor built the Taj Mahal?",
      options: ["Akbar", "Babur", "Aurangzeb", "Shah Jahan"],
      answer: "Shah Jahan",
    },
    {
      id: 207,
      topic: "History",
      question: "The Non-Aligned Movement was co-founded by which leader?",
      options: ["Mao Zedong", "Ho Chi Minh", "Josip Broz Tito", "Fidel Castro"],
      answer: "Josip Broz Tito",
    },
    {
      id: 208,
      topic: "History",
      question: "What was the 'Scramble for Africa' approximately dated to?",
      options: ["1800-1830", "1840-1870", "1881-1914", "1920-1940"],
      answer: "1881-1914",
    },
    {
      id: 209,
      topic: "History",
      question:
        "The Congress of Vienna (1815) was chaired by which Austrian statesman?",
      options: [
        "Prince Eugene",
        "Klemens von Metternich",
        "Emperor Franz I",
        "Friedrich von Gentz",
      ],
      answer: "Klemens von Metternich",
    },
    {
      id: 210,
      topic: "History",
      question:
        "Which dynasty ruled China during the construction of the Great Wall's most famous sections?",
      options: ["Han", "Tang", "Ming", "Qing"],
      answer: "Ming",
    },

    // Animals
    {
      id: 211,
      topic: "Animals",
      question:
        "What is the scientific term for animals that are active at twilight?",
      options: ["Nocturnal", "Diurnal", "Crepuscular", "Cathemeral"],
      answer: "Crepuscular",
    },
    {
      id: 212,
      topic: "Animals",
      question:
        "Which animal has the most complex brain relative to its body size?",
      options: ["Dolphin", "Chimpanzee", "Crow", "Treeshrew"],
      answer: "Treeshrew",
    },
    {
      id: 213,
      topic: "Animals",
      question:
        "What is the biological term for organisms that can survive both in water and on land?",
      options: ["Reptiles", "Aquatics", "Amphibians", "Dipnoi"],
      answer: "Amphibians",
    },
    {
      id: 214,
      topic: "Animals",
      question:
        "The mimic octopus can impersonate which animals to deter predators?",
      options: [
        "Sharks and eels",
        "Flatfish, lionfish, and sea snakes",
        "Sea turtles and rays",
        "Jellyfish and starfish",
      ],
      answer: "Flatfish, lionfish, and sea snakes",
    },
    {
      id: 215,
      topic: "Animals",
      question:
        "What protein makes up the structure of bird feathers and human fingernails?",
      options: ["Collagen", "Keratin", "Elastin", "Fibrin"],
      answer: "Keratin",
    },
    {
      id: 216,
      topic: "Animals",
      question:
        "Which biological process do tardigrades use to survive extreme conditions?",
      options: ["Dormancy", "Cryptobiosis", "Hypothermia", "Anhydrobiosis"],
      answer: "Cryptobiosis",
    },
    {
      id: 217,
      topic: "Animals",
      question: "The lyrebird is famous for what ability?",
      options: [
        "Flying backwards",
        "Mimicking sounds with extreme accuracy",
        "Changing skin color",
        "Walking on water",
      ],
      answer: "Mimicking sounds with extreme accuracy",
    },
    {
      id: 218,
      topic: "Animals",
      question:
        "What is the symbiotic relationship between a clownfish and sea anemone classified as?",
      options: ["Parasitism", "Commensalism", "Mutualism", "Competition"],
      answer: "Mutualism",
    },
    {
      id: 219,
      topic: "Animals",
      question: "Which mammal has the highest blood pressure?",
      options: ["Elephant", "Giraffe", "Blue Whale", "Horse"],
      answer: "Giraffe",
    },
    {
      id: 220,
      topic: "Animals",
      question:
        "Which marine animal navigates using the Earth's magnetic field AND polarized light?",
      options: ["Shark", "Turtle", "Dolphin", "Mantis Shrimp"],
      answer: "Mantis Shrimp",
    },

    // Geopolitics
    {
      id: 221,
      topic: "Geopolitics",
      question: "The Montevideo Convention (1933) defined which concept?",
      options: [
        "Maritime borders",
        "Statehood criteria in international law",
        "Diplomatic immunity",
        "Refugee rights",
      ],
      answer: "Statehood criteria in international law",
    },
    {
      id: 222,
      topic: "Geopolitics",
      question:
        "What does the Westphalian system of sovereignty primarily assert?",
      options: [
        "Democracy as universal principle",
        "Non-interference in other states' internal affairs",
        "Free trade between nations",
        "Human rights precedence over borders",
      ],
      answer: "Non-interference in other states' internal affairs",
    },
    {
      id: 223,
      topic: "Geopolitics",
      question:
        "Which geopolitical theory argues that control of the Eurasian 'Heartland' equals world dominance?",
      options: [
        "Rimland Theory",
        "Sea Power Theory",
        "Heartland Theory",
        "Domino Theory",
      ],
      answer: "Heartland Theory",
    },
    {
      id: 224,
      topic: "Geopolitics",
      question:
        "The Responsibility to Protect (R2P) doctrine was adopted in which year?",
      options: ["1998", "2001", "2005", "2009"],
      answer: "2005",
    },
    {
      id: 225,
      topic: "Geopolitics",
      question:
        "Which international agreement set limits on conventional arms in Europe?",
      options: ["INF Treaty", "CFE Treaty", "New START", "Oslo Accords"],
      answer: "CFE Treaty",
    },
    {
      id: 226,
      topic: "Geopolitics",
      question: "The Triffin Dilemma describes a tension inherent in:",
      options: [
        "Military alliances",
        "Reserve currency status",
        "Trade surplus nations",
        "Nuclear proliferation",
      ],
      answer: "Reserve currency status",
    },
    {
      id: 227,
      topic: "Geopolitics",
      question: "What is the 'Thucydides Trap' concept used to explain?",
      options: [
        "Economic recessions",
        "The risk of war when a rising power challenges a dominant power",
        "Civil wars in fragile states",
        "Colonial legacy disputes",
      ],
      answer: "The risk of war when a rising power challenges a dominant power",
    },
    {
      id: 228,
      topic: "Geopolitics",
      question: "Which country has the most overseas military bases?",
      options: ["Russia", "China", "France", "United States"],
      answer: "United States",
    },
    {
      id: 229,
      topic: "Geopolitics",
      question: "QUAD alliance consists of which four countries?",
      options: [
        "US, UK, France, Germany",
        "US, Japan, India, Australia",
        "US, Canada, Japan, South Korea",
        "US, India, Israel, UAE",
      ],
      answer: "US, Japan, India, Australia",
    },
    {
      id: 230,
      topic: "Geopolitics",
      question: "The Kiel Canal connects which two bodies of water?",
      options: [
        "North Sea and Baltic Sea",
        "Atlantic and North Sea",
        "Baltic and Black Sea",
        "Mediterranean and Adriatic",
      ],
      answer: "North Sea and Baltic Sea",
    },

    // Math
    {
      id: 231,
      topic: "Math",
      question: "What is the Riemann Hypothesis about?",
      options: [
        "The distribution of prime numbers",
        "The shape of black holes",
        "Infinite series convergence",
        "Quantum probability",
      ],
      answer: "The distribution of prime numbers",
    },
    {
      id: 232,
      topic: "Math",
      question: "What does Bayes' Theorem calculate?",
      options: [
        "Standard deviation",
        "Correlation coefficient",
        "Conditional probability",
        "Matrix determinant",
      ],
      answer: "Conditional probability",
    },
    {
      id: 233,
      topic: "Math",
      question: "A Möbius strip has how many sides?",
      options: ["0", "1", "2", "3"],
      answer: "1",
    },
    {
      id: 234,
      topic: "Math",
      question: "What is the significance of the number 'e' (Euler's number)?",
      options: [
        "The base of natural logarithms",
        "The ratio of circumference to diameter",
        "The square root of -1",
        "Planck's constant",
      ],
      answer: "The base of natural logarithms",
    },
    {
      id: 235,
      topic: "Math",
      question:
        "Gödel's Incompleteness Theorem states that in any consistent formal system:",
      options: [
        "All truths can be proven",
        "Some true statements cannot be proven",
        "Math is inconsistent",
        "Infinity cannot be formalized",
      ],
      answer: "Some true statements cannot be proven",
    },
    {
      id: 236,
      topic: "Math",
      question: "What is the integral of e^x dx?",
      options: ["xe^x + C", "e^x + C", "e^(x+1)/(x+1) + C", "1/e^x + C"],
      answer: "e^x + C",
    },
    {
      id: 237,
      topic: "Math",
      question: "What is P(A∪B) in probability theory?",
      options: [
        "P(A) × P(B)",
        "P(A) + P(B) - P(A∩B)",
        "P(A) - P(B)",
        "P(A) + P(B)",
      ],
      answer: "P(A) + P(B) - P(A∩B)",
    },
    {
      id: 238,
      topic: "Math",
      question: "Which branch of math deals with continuous change?",
      options: ["Topology", "Number Theory", "Calculus", "Abstract Algebra"],
      answer: "Calculus",
    },
    {
      id: 239,
      topic: "Math",
      question: "What is the Four Color Theorem?",
      options: [
        "All shapes have 4 symmetries",
        "Any map can be colored using 4 colors so no adjacent regions share a color",
        "4 points define all Euclidean geometry",
        "There are exactly 4 types of symmetry groups",
      ],
      answer:
        "Any map can be colored using 4 colors so no adjacent regions share a color",
    },
    {
      id: 240,
      topic: "Math",
      question: "What is a 'Hamiltonian path' in graph theory?",
      options: [
        "The shortest path between two nodes",
        "A path visiting every vertex exactly once",
        "A loop returning to the starting vertex",
        "A minimum spanning tree",
      ],
      answer: "A path visiting every vertex exactly once",
    },

    // Coding
    {
      id: 241,
      topic: "Coding",
      question: "What is the CAP theorem in distributed systems?",
      options: [
        "Consistency, Availability, Partition tolerance – you can only guarantee 2 of 3",
        "CPU, Architecture, Protocol principles",
        "Cache, API, Persistence constraints",
        "Clustering, Automation, Processing trade-offs",
      ],
      answer:
        "Consistency, Availability, Partition tolerance – you can only guarantee 2 of 3",
    },
    {
      id: 242,
      topic: "Coding",
      question: "What is a 'monad' in functional programming?",
      options: [
        "A type of loop",
        "A design pattern for handling computations with context",
        "An immutable variable",
        "A method of recursion",
      ],
      answer: "A design pattern for handling computations with context",
    },
    {
      id: 243,
      topic: "Coding",
      question: "What does ACID stand for in database transactions?",
      options: [
        "Atomicity, Consistency, Isolation, Durability",
        "Availability, Consistency, Integrity, Distribution",
        "Atomicity, Concurrency, Independence, Data",
        "Access, Control, Integrity, Durability",
      ],
      answer: "Atomicity, Consistency, Isolation, Durability",
    },
    {
      id: 244,
      topic: "Coding",
      question: "What is 'memoization' in programming?",
      options: [
        "Writing comments in code",
        "Caching results of expensive function calls",
        "Memory allocation technique",
        "Garbage collection strategy",
      ],
      answer: "Caching results of expensive function calls",
    },
    {
      id: 245,
      topic: "Coding",
      question: "Which cryptographic protocol ensures forward secrecy?",
      options: [
        "RSA key exchange",
        "Diffie-Hellman ephemeral key exchange",
        "MD5 hashing",
        "AES encryption",
      ],
      answer: "Diffie-Hellman ephemeral key exchange",
    },
    {
      id: 246,
      topic: "Coding",
      question: "What is the NP-complete problem class?",
      options: [
        "Problems solvable in polynomial time",
        "Problems verifiable in polynomial time with no known polynomial solution",
        "Problems with no solution",
        "Problems solvable only with quantum computers",
      ],
      answer:
        "Problems verifiable in polynomial time with no known polynomial solution",
    },
    {
      id: 247,
      topic: "Coding",
      question: "In the context of neural networks, what is 'backpropagation'?",
      options: [
        "Running the network in reverse",
        "Algorithm to compute gradients for weight updates",
        "Reversing the input data",
        "Resetting neural network weights",
      ],
      answer: "Algorithm to compute gradients for weight updates",
    },
    {
      id: 248,
      topic: "Coding",
      question: "What is a 'race condition' in concurrent programming?",
      options: [
        "Two threads competing for CPU",
        "Output depends on unpredictable ordering of operations",
        "A deadlock between processes",
        "Memory corruption from overflow",
      ],
      answer: "Output depends on unpredictable ordering of operations",
    },
    {
      id: 249,
      topic: "Coding",
      question: "What is the purpose of a Bloom filter?",
      options: [
        "Color filtering in graphics",
        "Probabilistic data structure to test set membership",
        "Sorting large datasets",
        "Compressing files",
      ],
      answer: "Probabilistic data structure to test set membership",
    },
    {
      id: 250,
      topic: "Coding",
      question:
        "Which consistency model allows reading stale data but provides high availability?",
      options: [
        "Strong consistency",
        "Linearizability",
        "Eventual consistency",
        "Sequential consistency",
      ],
      answer: "Eventual consistency",
    },

    // Science
    {
      id: 251,
      topic: "Science",
      question: "What is the Chandrasekhar limit?",
      options: [
        "The maximum temperature of a star",
        "The mass limit beyond which a white dwarf collapses into a neutron star",
        "The minimum mass for nuclear fusion",
        "The event horizon radius of a black hole",
      ],
      answer:
        "The mass limit beyond which a white dwarf collapses into a neutron star",
    },
    {
      id: 252,
      topic: "Science",
      question: "What is quantum entanglement?",
      options: [
        "Particles sharing the same location",
        "Two particles sharing quantum states instantaneously across any distance",
        "The collapse of a wave function",
        "Heisenberg's uncertainty principle applied to pairs",
      ],
      answer:
        "Two particles sharing quantum states instantaneously across any distance",
    },
    {
      id: 253,
      topic: "Science",
      question:
        "What is the difference between type I and type II superconductors?",
      options: [
        "Type I has higher resistance",
        "Type I expels all magnetic fields; type II allows partial flux penetration",
        "Type II operates at higher temperatures",
        "They are identical in behavior",
      ],
      answer:
        "Type I expels all magnetic fields; type II allows partial flux penetration",
    },
    {
      id: 254,
      topic: "Science",
      question: "What causes the 'observer effect' in quantum mechanics?",
      options: [
        "The presence of a scientist",
        "Measurement interacts with and disturbs the system",
        "Light speed limitations",
        "Electromagnetic interference",
      ],
      answer: "Measurement interacts with and disturbs the system",
    },
    {
      id: 255,
      topic: "Science",
      question:
        "What is the primary molecule involved in energy transfer within cells?",
      options: ["DNA", "RNA", "Glucose", "ATP"],
      answer: "ATP",
    },
    {
      id: 256,
      topic: "Science",
      question: "What does the Pauli Exclusion Principle state?",
      options: [
        "No two electrons can occupy the same quantum state simultaneously",
        "Electrons travel in fixed orbits",
        "All particles have equal probability distributions",
        "Energy is conserved in closed systems",
      ],
      answer:
        "No two electrons can occupy the same quantum state simultaneously",
    },
    {
      id: 257,
      topic: "Science",
      question: "What is the Standard Model in physics?",
      options: [
        "A framework for classical mechanics",
        "The theory describing fundamental particles and forces (except gravity)",
        "Einstein's field equations",
        "The theory of relativity",
      ],
      answer:
        "The theory describing fundamental particles and forces (except gravity)",
    },
    {
      id: 258,
      topic: "Science",
      question: "CRISPR-Cas9 is best described as:",
      options: [
        "A cancer treatment drug",
        "A gene-editing tool using a bacterial immune mechanism",
        "A protein folding algorithm",
        "A DNA sequencing technology",
      ],
      answer: "A gene-editing tool using a bacterial immune mechanism",
    },
    {
      id: 259,
      topic: "Science",
      question: "What is Hawking radiation?",
      options: [
        "UV radiation from black holes",
        "Theoretical thermal radiation emitted by black holes due to quantum effects",
        "X-rays emitted by neutron stars",
        "Radio waves from pulsars",
      ],
      answer:
        "Theoretical thermal radiation emitted by black holes due to quantum effects",
    },
    {
      id: 260,
      topic: "Science",
      question: "In thermodynamics, the second law states:",
      options: [
        "Energy is conserved",
        "Entropy of an isolated system always increases",
        "Heat flows from hot to cold only",
        "PV = nRT",
      ],
      answer: "Entropy of an isolated system always increases",
    },

    // General Knowledge
    {
      id: 261,
      topic: "General",
      question: "In linguistics, what is the Sapir-Whorf hypothesis?",
      options: [
        "All languages share universal grammar",
        "Language shapes the way we think and perceive reality",
        "Children learn language through reinforcement",
        "Syntax is innate in humans",
      ],
      answer: "Language shapes the way we think and perceive reality",
    },
    {
      id: 262,
      topic: "General",
      question: "What is the 'Ship of Theseus' paradox about?",
      options: [
        "Navigation without maps",
        "Whether an object that has had all components replaced remains fundamentally the same",
        "Immortality through cloning",
        "Paradoxes of time travel",
      ],
      answer:
        "Whether an object that has had all components replaced remains fundamentally the same",
    },
    {
      id: 263,
      topic: "General",
      question: "The Flynn Effect describes:",
      options: [
        "The decline of IQ over generations",
        "The rise in average IQ scores over time",
        "The correlation between IQ and income",
        "Genetic heritability of intelligence",
      ],
      answer: "The rise in average IQ scores over time",
    },
    {
      id: 264,
      topic: "General",
      question:
        "What economic phenomenon does 'creative destruction' describe?",
      options: [
        "Government spending boosts",
        "Innovations disrupting and replacing existing industries",
        "Trade wars damaging economies",
        "Financial bubbles collapsing",
      ],
      answer: "Innovations disrupting and replacing existing industries",
    },
    {
      id: 265,
      topic: "General",
      question: "The Dunning-Kruger effect describes:",
      options: [
        "Experts underestimating complexity",
        "Unskilled people overestimating their competence",
        "Memory distortion over time",
        "Emotional intelligence barriers",
      ],
      answer: "Unskilled people overestimating their competence",
    },
    {
      id: 266,
      topic: "General",
      question:
        "Which philosopher proposed the concept of 'Categorical Imperative'?",
      options: ["Hume", "Nietzsche", "Kant", "Locke"],
      answer: "Kant",
    },
    {
      id: 267,
      topic: "General",
      question:
        "What is the name of the logical fallacy of assuming something is true because it hasn't been proven false?",
      options: [
        "Ad hominem",
        "Straw man",
        "Argument from ignorance",
        "False dilemma",
      ],
      answer: "Argument from ignorance",
    },
    {
      id: 268,
      topic: "General",
      question: "The Baader-Meinhof phenomenon is also known as:",
      options: [
        "Déjà vu",
        "Frequency illusion",
        "Confirmation bias",
        "Gambler's fallacy",
      ],
      answer: "Frequency illusion",
    },
    {
      id: 269,
      topic: "General",
      question: "What does the Turing Test evaluate?",
      options: [
        "Computer processing speed",
        "Whether a machine can exhibit intelligent behavior indistinguishable from a human",
        "Cybersecurity strength",
        "Algorithm efficiency",
      ],
      answer:
        "Whether a machine can exhibit intelligent behavior indistinguishable from a human",
    },
    {
      id: 270,
      topic: "General",
      question: "Fermat's Last Theorem was finally proven in which year?",
      options: ["1965", "1977", "1995", "2003"],
      answer: "1995",
    },
    {
      id: 271,
      topic: "History",
      question:
        "The Battle of Adwa (1896) was significant because it resulted in:",
      options: [
        "British conquest of Ethiopia",
        "Ethiopia defeating Italy and remaining independent",
        "France colonizing East Africa",
        "The end of the Scramble for Africa",
      ],
      answer: "Ethiopia defeating Italy and remaining independent",
    },
    {
      id: 272,
      topic: "Science",
      question: "What is the anthropic principle in cosmology?",
      options: [
        "Humans will colonize the universe",
        "The universe's properties allow for the existence of conscious observers",
        "Life exists only on Earth",
        "The universe is infinite",
      ],
      answer:
        "The universe's properties allow for the existence of conscious observers",
    },
    {
      id: 273,
      topic: "Coding",
      question: "What is a Byzantine fault in distributed computing?",
      options: [
        "A server that is too slow",
        "A component that fails in an arbitrary or malicious way",
        "Network partition between nodes",
        "Data corruption due to disk failure",
      ],
      answer: "A component that fails in an arbitrary or malicious way",
    },
    {
      id: 274,
      topic: "Math",
      question: "What does Fermat's Little Theorem state?",
      options: [
        "No integer solutions exist for aⁿ+bⁿ=cⁿ (n>2)",
        "For prime p, a^p ≡ a (mod p)",
        "Every even integer > 2 is a sum of two primes",
        "There are infinitely many twin primes",
      ],
      answer: "For prime p, a^p ≡ a (mod p)",
    },
    {
      id: 275,
      topic: "Geopolitics",
      question:
        "The Sykes-Picot Agreement (1916) primarily shaped borders in which region?",
      options: [
        "Sub-Saharan Africa",
        "Southeast Asia",
        "The Middle East",
        "Central Asia",
      ],
      answer: "The Middle East",
    },
    {
      id: 276,
      topic: "Animals",
      question: "What sensory organ do sharks use to detect electrical fields?",
      options: [
        "Lateral line",
        "Ampullae of Lorenzini",
        "Pit organs",
        "Jacobson's organ",
      ],
      answer: "Ampullae of Lorenzini",
    },
    {
      id: 277,
      topic: "Science",
      question: "What is the Higgs boson often referred to as?",
      options: [
        "The God Particle",
        "The Dark Particle",
        "The Force Carrier",
        "The Gravity Particle",
      ],
      answer: "The God Particle",
    },
    {
      id: 278,
      topic: "Coding",
      question:
        "Which theorem is foundational to public-key cryptography (RSA)?",
      options: [
        "Fermat's Last Theorem",
        "Euler's Theorem",
        "Pythagorean Theorem",
        "Bayes' Theorem",
      ],
      answer: "Euler's Theorem",
    },
    {
      id: 279,
      topic: "History",
      question:
        "The Bretton Woods Conference (1944) established which institutions?",
      options: [
        "NATO and the UN",
        "IMF and World Bank",
        "GATT and WTO",
        "UNESCO and WHO",
      ],
      answer: "IMF and World Bank",
    },
    {
      id: 280,
      topic: "General",
      question: "What is the 'P vs NP' problem?",
      options: [
        "A networking protocol debate",
        "Whether every problem verifiable in polynomial time is also solvable in polynomial time",
        "A parallel vs. sequential computing question",
        "A database optimization challenge",
      ],
      answer:
        "Whether every problem verifiable in polynomial time is also solvable in polynomial time",
    },
    {
      id: 281,
      topic: "Science",
      question:
        "What phenomenon causes the precession of Mercury's perihelion that Newtonian mechanics couldn't explain?",
      options: [
        "Tidal forces from Venus",
        "General Relativity's spacetime curvature",
        "Solar magnetic fields",
        "The influence of dark matter",
      ],
      answer: "General Relativity's spacetime curvature",
    },
    {
      id: 282,
      topic: "Math",
      question:
        "What is the name for the branch of mathematics studying properties preserved under continuous deformations?",
      options: [
        "Algebra",
        "Topology",
        "Differential Geometry",
        "Number Theory",
      ],
      answer: "Topology",
    },
    {
      id: 283,
      topic: "History",
      question:
        "The Nuremberg Laws (1935) stripped citizenship from which group?",
      options: [
        "Communists",
        "Slavic peoples",
        "Jewish Germans",
        "Gypsies (Roma)",
      ],
      answer: "Jewish Germans",
    },
    {
      id: 284,
      topic: "Coding",
      question: "What is 'sharding' in database architecture?",
      options: [
        "Encrypting data at rest",
        "Horizontal partitioning of data across multiple databases",
        "Caching frequently accessed data",
        "Replicating data to backup servers",
      ],
      answer: "Horizontal partitioning of data across multiple databases",
    },
    {
      id: 285,
      topic: "Geopolitics",
      question:
        "The principle of 'comparative advantage' in trade was developed by:",
      options: [
        "Adam Smith",
        "Karl Marx",
        "David Ricardo",
        "John Maynard Keynes",
      ],
      answer: "David Ricardo",
    },
    {
      id: 286,
      topic: "Animals",
      question:
        "What is the biological term for the shedding of an exoskeleton in arthropods?",
      options: ["Metamorphosis", "Ecdysis", "Autotomy", "Aposematism"],
      answer: "Ecdysis",
    },
    {
      id: 287,
      topic: "Science",
      question: "What does 'RNA interference' (RNAi) do in biology?",
      options: [
        "Edits DNA sequences",
        "Silences gene expression via small RNA molecules",
        "Converts RNA to DNA",
        "Manufactures proteins",
      ],
      answer: "Silences gene expression via small RNA molecules",
    },
    {
      id: 288,
      topic: "General",
      question: "The Overton Window refers to:",
      options: [
        "A media bias measurement tool",
        "The range of policies politically acceptable to the public at a given time",
        "A statistical method for polling",
        "A theory about window dressing in economics",
      ],
      answer:
        "The range of policies politically acceptable to the public at a given time",
    },
    {
      id: 289,
      topic: "History",
      question: "The Partition of India in 1947 created which two nations?",
      options: [
        "India and Bangladesh",
        "India and Pakistan",
        "Pakistan and Sri Lanka",
        "India and Nepal",
      ],
      answer: "India and Pakistan",
    },
    {
      id: 290,
      topic: "Coding",
      question: "What is a 'hash collision'?",
      options: [
        "Network collision in older protocols",
        "Two different inputs producing the same hash output",
        "A failed encryption attempt",
        "A corrupted database entry",
      ],
      answer: "Two different inputs producing the same hash output",
    },
    {
      id: 291,
      topic: "Science",
      question:
        "What is the 'many-worlds interpretation' in quantum mechanics?",
      options: [
        "The universe is one of many universes",
        "Every quantum event causes the universe to split into parallel branches",
        "Parallel dimensions have different physical laws",
        "Time travel creates alternate realities",
      ],
      answer:
        "Every quantum event causes the universe to split into parallel branches",
    },
    {
      id: 292,
      topic: "Math",
      question: "What is the Collatz Conjecture?",
      options: [
        "Every even number is a sum of two primes",
        "Starting with any positive integer, repeated n/2 or 3n+1 steps always reach 1",
        "All odd perfect numbers are infinite",
        "Prime numbers follow a fixed distribution",
      ],
      answer:
        "Starting with any positive integer, repeated n/2 or 3n+1 steps always reach 1",
    },
    {
      id: 293,
      topic: "Geopolitics",
      question: "What does 'extraterritoriality' mean in international law?",
      options: [
        "Space jurisdiction claims",
        "Diplomatic immunity",
        "Citizens subject to home country laws when abroad",
        "Territorial waters beyond 12 miles",
      ],
      answer: "Citizens subject to home country laws when abroad",
    },
    {
      id: 294,
      topic: "Animals",
      question: "What is 'eusociality' in animal behavior?",
      options: [
        "Animals that mate for life",
        "Cooperative brood care with reproductive division of labor",
        "Herd behavior in mammals",
        "Solitary animals defending territory",
      ],
      answer: "Cooperative brood care with reproductive division of labor",
    },
    {
      id: 295,
      topic: "History",
      question:
        "Which thinker coined the phrase 'survival of the fittest' (later associated with Darwin)?",
      options: [
        "Thomas Huxley",
        "Charles Darwin",
        "Herbert Spencer",
        "Alfred Russel Wallace",
      ],
      answer: "Herbert Spencer",
    },
    {
      id: 296,
      topic: "Science",
      question: "What is 'spontaneous symmetry breaking' in physics?",
      options: [
        "A particle randomly decaying",
        "A system adopting a less symmetric state despite symmetric laws",
        "Electrons randomly changing spin",
        "Quantum tunneling phenomena",
      ],
      answer: "A system adopting a less symmetric state despite symmetric laws",
    },
    {
      id: 297,
      topic: "Coding",
      question: "What is the difference between a process and a thread?",
      options: [
        "There is no difference",
        "A process has its own memory space; threads share memory within a process",
        "Threads are slower than processes",
        "Processes run on GPU; threads on CPU",
      ],
      answer:
        "A process has its own memory space; threads share memory within a process",
    },
    {
      id: 298,
      topic: "General",
      question:
        "The 'Trolley Problem' is a classic thought experiment in which field?",
      options: [
        "Physics",
        "Psychology",
        "Ethics/Moral Philosophy",
        "Economics",
      ],
      answer: "Ethics/Moral Philosophy",
    },
    {
      id: 299,
      topic: "Geopolitics",
      question:
        "What is 'dollar hegemony' or 'exorbitant privilege' in global economics?",
      options: [
        "US tariff advantages",
        "The economic advantage of the US dollar as the world's reserve currency",
        "America's military deterrence",
        "The IMF's control over exchange rates",
      ],
      answer:
        "The economic advantage of the US dollar as the world's reserve currency",
    },
    {
      id: 300,
      topic: "Science",
      question: "What is the function of telomeres in DNA?",
      options: [
        "Encoding proteins",
        "Protecting chromosome ends from deterioration during replication",
        "Facilitating RNA transcription",
        "Regulating gene expression",
      ],
      answer:
        "Protecting chromosome ends from deterioration during replication",
    },
  ],
};

export default quizData;
